### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by gregoiregentil** [luuhai48/gmail-oauth2#1]
I'm running composer require luuhai48/gmail-oauth2 and I get the following error:

`
Problem 1
    - Root composer.json requires luuhai48/gmail-oauth2 ^1.0 -> satisfiable by luuhai48/gmail-oauth2[v1.0.0].
    - luuhai48/gmail-oauth2 v1.0.0 requires flarum/core ^0.1.0-beta.14 -> found flarum/core[v0.1.0-beta.14, v0.1.0-beta.14.1, v0.1.0-beta.15, v0.1.0-beta.16] but it does not match your minimum-stability.
`

Am I doing anything wrong? I have Flarum 1.6.

**Comment by luuhai48** [comment]
@gregoiregentil this project is now deprecated. Google oauth is available in official extension.
https://github.com/FriendsOfFlarum/oauth

**Comment by gregoiregentil** [comment]
I'm still confused. I have installed that extension. But what I want to accomplish is to send emails via the gmail account. I don't think that the FoF extension can do that. Can you please clarify?

**Comment by luuhai48** [comment]
you can clone this repo, try changing the require inside `composer.json` to `"flarum/core": "^1.6"`
